#!/bin/bash
set -e
MIX=mix
if (which rtx > /dev/null); then
    MIX="$(rtx which mix)"
elif [ -f "$HOME"/.asdf/asdf.sh ]; then
    MIX="$HOME/.asdf/bin/mix"
fi

if "$MIX" format --check-formatted; then
    true
else
    "$MIX" format --check-equivalent
    false
fi
"$MIX" credo --strict --format oneline
env MIX_ENV=test "$MIX" do compile --force --warnings-as-errors, test --no-color
"$MIX" dialyzer --format dialyxir
