name: Deploy to ECS (Production)

on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: prod
    concurrency: prod
    steps:
    - uses: actions/checkout@v4
    - uses: mbta/actions/build-push-ecr@v2
      id: build-push
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        docker-repo: ${{ secrets.DOCKER_REPO }}
    - uses: mbta/actions/deploy-ecs@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        ecs-cluster: tablespoon
        ecs-service: tablespoon-prod
        docker-tag: ${{ steps.build-push.outputs.docker-tag }}
    - uses: mbta/actions/notify-slack-deploy@v2
      if: ${{ !cancelled() }}
      with:
        webhook-url: ${{ secrets.SLACK_WEBHOOK }}
        job-status: ${{ job.status }}
