name: Deploy to ECS (Production)

on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod
    concurrency: prod
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Fetch configuration
      run: |
        aws s3 cp s3://${{ secrets.CONFIG_BUCKET }}/tablespoon/prod.secret.exs config/prod.secret.exs
    - uses: mbta/actions/build-push-ecr@v1
      id: build-push
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        docker-repo: ${{ secrets.DOCKER_REPO }}
    - uses: mbta/actions/deploy-ecs@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ecs-cluster: tablespoon
        ecs-service: tablespoon-prod
        docker-tag: ${{ steps.build-push.outputs.docker-tag }}
    - uses: mbta/actions/notify-slack-deploy@v1
      if: ${{ !cancelled() }}
      with:
        webhook-url: ${{ secrets.SLACK_WEBHOOK }}
        job-status: ${{ job.status }}
