name: Docker

on:
  push:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t tablespoon .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          image-ref: tablespoon
          trivy-config: trivy.yml
