name: Docker

on: [push]

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Fetch configuration
      run: |
        aws s3 cp s3://${{ secrets.CONFIG_BUCKET }}/tablespoon/prod.secret.exs config/prod.secret.exs
    - run: docker build .
