name: Deploy Stunnel

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency: prod-linux
    env:
      ECS_CLUSTER: linux-prod
      ECS_SERVICE: stunnel-prod

    steps:
      - uses: actions/checkout@v4
      - uses: mbta/actions/deploy-ecs@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          ecs-cluster: ${{ env.ECS_CLUSTER }}
          ecs-service: ${{ env.ECS_SERVICE }}
          docker-tag: ghcr.io/mbta/stunnel:5.72-r0-alpine-3.19.1
          launch-type: EXTERNAL
      - uses: mbta/actions/notify-slack-deploy@v1
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
