name: Deploy Stunnel

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    uses: mbta/workflows/.github/workflows/deploy-on-prem.yml@main
    with:
      docker-tag: 5.67-windows-1809
      app-name: stunnel
      environment: prod
      on-prem-cluster: hsctd-prod-managers
      splunk-index: tablespoon-prod
      task-cpu: 0.25
      task-memory: 256M
      task-port: 8080 9005
      update-order: start-first
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      docker-repo: mbtatools/windows-stunnel
