name: Report Elixir Coverage

on:
  workflow_run:
    workflows:
      - Elixir CI
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # private repo, needs permission to read

jobs:
  report-coverage:
    name: Reports Exilir Coverage
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p ${RUNNER_TEMP}/cover
        permissions:
          pull-requests: write # needed for coverage reports
        env:
          RUNNER_TEMP: ${{ runner.temp }}
      - name: Log Fetch Request 
        run: echo Fetching artifacts for ${GITHUB_EVENT_WORKFLOW_ID}, event name ${GITHUB_EVENT_NAME}, triggered by ${GITHUB_EVENT_WORKFLOW_EVENT}
        env:
          GITHUB_EVENT_WORKFLOW_ID: ${{ github.event.workflow_run.id }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_WORKFLOW_EVENT: ${{ github.event.workflow_run.event }}
      - name: Download artifact
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${GITHUB_EVENT_WORKFLOW_ID},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "elixir-lcov"
            })[0];
            var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${RUNNER_TEMP}/cover/elixir-lcov.zip', Buffer.from(download.data));
        env:
          GITHUB_EVENT_WORKFLOW_ID: ${{ github.event.workflow_run.id }}
          RUNNER_TEMP: ${{ runner.temp }}
      - working-directory: ${{ runner.temp }}/cover
        id: pr_vars
        run: |
          unzip elixir-lcov.zip
          echo "PR_SHA=$(cat PR_SHA)" >> $GITHUB_OUTPUT
          echo "PR_NUMBER=$(cat PR_NUMBER)" >> $GITHUB_OUTPUT
      # UNTRUSTED CODE - do not run scripts from it
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ steps.pr_vars.outputs.PR_SHA }}
      - name: Upload coverage artifact and post comment
        uses: mbta/github-actions-report-lcov@44a478dc20d1b62bf0f8f13951f3dc20bacbda19 # v4.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-files: ${{ runner.temp }}/cover/lcov*.info
          artifact-name: elixir-code-coverage
